# Postgres compose file

version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    restart: always
